version: "3"
services: 
  backend: 
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports: 
      - "3001:3001"
    networks:
      - qdub
    volumes:
      - ./server/src:/app/src:ro
    args: ["--dockerfile=./Dockerfile",
            "--context=./server"]
  frontend: 
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-app
    stdin_open: true
    tty: true
    ports:  
      - "3000:3000"
    volumes: 
      - ./client/src:/app/src:ro
    environment:
      - REACT_APP_NAME=Qdup
    restart: always
    networks:
      - qdub
    args: ["--dockerfile=./Dockerfile",
      "--context=./client"]
networks:
  qdub:
    driver: bridge
volumes:
  db-data:
