name: Qdup-backend-test

on: 
  push:
    branchs: 
      - 'alpha-fullstack'

jobs: 
  backend-unit-test:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
        working-directory: server/
      - name: Install Mocha and chai
        run: npm install mocha chai --save-dev     
      - name: Compile test files
        run: tsc
      - name: Run tests
        run: npm test
        working-directory: server/
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
        working-directory: client/
      - name: Install Jest
        run: npm install jest --save-dev     
      - name: Compile test files
        run: tsc
      - name: Run tests
        run: npm run test
        working-directory: client/